### PR TITLE
Aliasing system + Dynamic settings + Macro system + minor fixes and improvements

### PR DESCRIPTION
**Pull request by Centrifudge**
(This is my first ever contribution to FOSS so I don't know the etiquette sorry)

Notes for commit 1:
Minor changes:
Added "ok" and "why not" to agreeInput.
Added "rather not" to disagreeInput.
Converted website names to string (I assume the quotation marks were previously forgotten).
Major changes:
Added an aliasing system: users can now add aliases. which serve to convert one string of command into another.
Aliases are currently saved in res/aliases.txt in the format "triggerString=aliasTargetString\n".

Notes for commit 2-5:
Bugfixes (It took me a while to get a virtual environment properly setup to test my code).

Notes for commit 6-End:
In their descriptions.

### CODE REVIEW

**Comment by Centrifudge** [comment]
also corrected a typo in .gitignore where /.venv was spelled /venv

**Comment by Centrifudge** [comment]
@virejdasani Is this a correct contribution? I have tons of other ideas for the project so if you're interested let me know.

**Comment by Centrifudge** [comment]
@virejdasani What do you think? I think user extensions combined with aliases make it a hell of a lot more useful and I could very much see myself use Alexis on a GUIless distro.

**Comment by Centrifudge** [comment]
Hey @virejdasani is this repo still open to contributions?

**Comment by Centrifudge** [comment]
Hello  @virejdasani ; just wondering, is this repo still open to contributions? I love the concept and would like to contribute but if you're not open please tell me so that I just fork it.

**Comment by Centrifudge** [comment]
Only light and dark mode seem to be working properly, I'll try fixing the other colours soon although they are by no means unusable.

**Comment by Centrifudge** [comment]
The arguments added to the macros broke most of them, should be a simple fix though so expect it to be stable tomorrow.

**Comment by Centrifudge** [comment]
Just a small issue where all arguments are passed as lowercase, I'm on it though and the fact that macros already work as well as they do means that Alexis pretty much now has infinite potential.

**Comment by Centrifudge** [comment]
> also corrected a typo in .gitignore where /.venv was spelled /venv

Might want to add /venv back in depending on how you called it.

**Comment by virejdasani** [comment]
Hey, thanks for the contributions! Before I merge, can you give me a summary of everything you've added, changed, and deleted, please?

**Comment by Centrifudge** [comment]
> Hey, thanks for the contributions! Before I merge, can you give me a summary of everything you've added, changed, and deleted, please?

Sure thing! Here you go!

New files:
settings.txt: allows for users to modify program wide parameters such as background colour.
AllSetings.txt: functions similarly to allsettings.txt as a list of all available settings and there defaults
aliases.txt: list all user set aliases in key=value pairs
macros.txt: lists user defined macros
examplemacros.txt: provides examples of correctly written macros

*Code changes:

Aliasing system:
Users can set aliases for text (not just commands) which means that a string in a command will be understood as another string; it is important to note that aliasing takes priority over everything else so the original command is unknown to the rest of the program. User set aliased are stored in aliases.txt

Dealiasing:
Removes the any alias that targets the specified string from aliases.txt

Macros:
Users can create and execute custom python programs (supports arguments too) , these must be edited using an external program and are stored in macros.txt

Settings:
Users can define system wide parameters such as background colour, these must be set using an external program and are listed in settings.txt

+ Minor fixes

I hope his helps! If you have any questions feel free to ask me about the code here.

In the meantime, here are some question for you:
I've been thinking about adding an SLM (small language model) such as PHI-2 to make responses a lot more natural, would that be a welcome option (optional of course)? And maybe image generation too! So many ideas, so much potential! What about a G.U.I.?

PS: I'm challenging myself to 1 commit a day over the vacations so as soon as this gets merged expect a new pull request.

**Comment by Centrifudge** [comment]
Damn I sound A.I. generated

**Comment by Centrifudge** [comment]
@virejdasani Are you still here?

**Comment by virejdasani** [comment]
Hello, I have had a chance to go through the code in your commits. At this stage, I unfortunately, cannot merge because at a glance I saw, there are places in your code where you have added extra empty lines in the code, unnecessary full stop characters "." to sentences Alexis says, `endswith` "x" for twitter but there can be other commands that end with "x" which could be problematic, spelling errors etc.

I appreciate your contributions and they look quite impressive but I cannot merge till your code is up to 
the required standards. I am not closing this PR because if you can fix all these concerns, I'll go ahead with the merge.

Thank you again for contributing :)

**Comment by Centrifudge** [comment]
> Hello, I have had a chance to go through the code in your commits. At this stage, I unfortunately, cannot merge because at a glance I saw, there are places in your code where you have added extra empty lines in the code, unnecessary full stop characters "." to sentences Alexis says, `endswith` "x" for twitter but there can be other commands that end with "x" which could be problematic, spelling errors etc.
> 
> I appreciate your contributions and they look quite impressive but I cannot merge till your code is up to the required standards. I am not closing this PR because if you can fix all these concerns, I'll go ahead with the merge.
> 
> Thank you again for contributing :)

Hi again, it would seem I haven't checked in in a while, anyways.
I understand your concern for the .endswith("x.") however, after review I believe that since this check is only performed if the user requests the opening of a website and very few words or website names end in "x" I believe that it is safe to perform these checks. If one would want to add a conflicting website then I believe that simply checking for it prior to checking for X would fix any issue.
I will revert the changes in punctuation and the extra newlines if you wish.

I will be happy to further contribute to Alexis in the future.

**Comment by Centrifudge** [comment]
Here you go, I believe that everything that I did not change was legitimate. If you disagree feel free to let me know so that we can discuss it.

**Comment by Centrifudge** [comment]
@virejdasani Do you agree with the changes?
I still believe that we should keep the correct punctuation with full stops

**Comment by Centrifudge** [comment]
I'm pretty sure speech recognition is not functional, you might want to ask for an update from its original developer.

**Comment by Centrifudge** [comment]
@virejdasani Are you still open to the pull request by any chance?

**Comment by virejdasani** [comment]
Thank you so much and sorry for taking a while to get to this, been really busy with exams and work :)

**Pull request merged**
